include("../util/evidence_verification.jl")
include("cpd/conditionalprobabilitydistribution.jl")
include("inferencestate.jl")
include("factors.jl")
include("factor_methods.jl")
include("factor_algebra.jl")
include("variableselimination.jl")